### ISSUE TITLE
Remove redundant workflow on master

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/smatr#15]
This test from this workflow is failing but also no longer needed I think 

https://github.com/traitecoevo/smatr/blob/e7c1c4bff06ddf67e6cf9270adf7eb79959415e4/.github/workflows/check_r_version.yml

**Comment by fontikar** [comment]
I changed a single line in the r-check-version.yml and the error is gone 0725fb86a579dd97a0c69a48cc3c14ea691f3b6c. I am not 100% sure if this is redundant to the existing R-CMD-check. The former installs the package on two diff versions of R and the latter runs RMD check on different OS platforms if my deciphering of the code is correct? 

I was inspired by this post: https://community.rstudio.com/t/trouble-skipping-r-installation-in-setup-r-github-action-v1/77115/3

Need to work on understand the specfics of GH actions yml
