### ISSUE TITLE
Papers referenced in `slope.test` have they been published? 

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/smatr#18]
>  Tests if the line relating y to x has a slope equal to test.value (which has a default value of 1). The line can be a linear regression line, major axis or standardised major axis (as selected using the input argument choice).The test is carried out by testing for correlation between residual and fitted values, as described in **Warton et al (in review)**. 

> If measurement error is present, it can be corrected for through use of the input argument V, which makes adjustments to the estimated sample variances and covariances then proceeds with the same method of inference. Note, however, that this method is only approximate (see **Warton et al in review for more details**).

> Setting `robust = TRUE` fits lines using Huber's M estimation, and modifies the test statistic as proposed in **Taskinen & Warton** (in review).

Have the quoted paper been published? I can update these upon confirmation!

**Comment by dfalster** [comment]
Good catch Fonti!

I believe the refs should be 

Warton DI et al. (2006) Bivariate line-fitting methods for allometry. Biological Reviews 81: 259–291. DOI: [10.1017/S1464793106007007](https://doi.org/10.1017/S1464793106007007)

Taskinen S& Warton DI (2013) Robust tests for one or more allometric lines. Journal of Theoretical Biology 333: 38–46. DOI: [10.1016/j.jtbi.2013.05.010](https://doi.org/10.1016/j.jtbi.2013.05.010)
