### ISSUE TITLE
significant edits to pass CHECK

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/smatr#8]
Copied from bitbucket:

Remko Duursma REPO OWNER created an issue 2016-09-22
with recent R updates, the package check is more strict. Have to resolve this before submitting update to CRAN.

It may be worth switching to roxygen2 doc - even though this is a bit of work.

**Comment by dfalster** [comment]
Running `devtools::check` proceeds smoothly, while `R CMD check .` comes up with an error (possibly more). Which is best to go with for crab submission?

Also, I think rhub introduced some pre can checking capacity?

**Comment by fontikar** [comment]
devtools::check currently not passing for me, some issues with vignette building, possible due to #11 and recent migration to roxygen2! Will take a look tomorrow!

**Comment by fontikar** [comment]
devtools::check currently not passing on tests branch after #11 but also #6 now breaks building of the vignette!
